// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations",
    },
    datasource: {
        // Prisma CLI should prefer a direct connection for migrations when available.
        url: process.env["DATABASE_DIRECT_URL"] ?? process.env["DATABASE_URL"],
    },
});